model:
  embed_dim: 300
  hidden_dim: 256
  vocab_size: null
  num_answers: 50

training:
  num_epochs: 20
  batch_size: 32
  learning_rate: 0.001
  train_test_split: 0.8
  max_sequence_length: 20

dataset:
  name: "flaviagiammarino/vqa-rad"
  split: "train"
  top_answers: 50

device:
  use_cuda: true

models:
  blip2: "Salesforce/blip2-flan-t5-xl"
  translator: "facebook/nllb-200-distilled-600M"

languages:
  supported:
    - en
    - hi
    - te
    - ta
    - kn
    - ml
